import type { Product } from "./types"

// Cup candles data
export const products: Product[] = [
  // Cup Candles - 65g
  {
    id: "cup-gel-65",
    name: "Gel Wax Cup Candle - 65g",
    description: "A beautiful 65g gel wax candle in a glass cup that creates a stunning visual effect when lit.",
    category: "cup",
    waxType: "gel",
    weight: 65,
    price: 310,
    image: "/placeholder.svg?height=500&width=500",
    featured: true,
  },
  {
    id: "cup-palm-65",
    name: "Palm Wax Cup Candle - 65g",
    description: "A 65g palm wax candle in a glass cup, offering a clean and long-lasting burn.",
    category: "cup",
    waxType: "palm",
    weight: 65,
    price: 269,
    image: "/placeholder.svg?height=500&width=500",
  },
  {
    id: "cup-soy-65",
    name: "100% Natural Soy Wax Cup Candle - 65g",
    description: "A 65g pure soy wax candle in a glass cup, made from 100% natural ingredients.",
    category: "cup",
    waxType: "soy",
    weight: 65,
    price: 330,
    image: "/placeholder.svg?height=500&width=500",
  },

  // Cup Candles - 165g
  {
    id: "cup-gel-165",
    name: "Gel Wax Cup Candle - 165g",
    description: "A medium-sized 165g gel wax candle in a glass cup with beautiful clarity.",
    category: "cup",
    waxType: "gel",
    weight: 165,
    price: 404,
    image: "/placeholder.svg?height=500&width=500",
  },
  {
    id: "cup-palm-165",
    name: "Palm Wax Cup Candle - 165g",
    description: "A 165g palm wax candle in a glass cup, perfect for everyday use.",
    category: "cup",
    waxType: "palm",
    weight: 165,
    price: 360,
    image: "/placeholder.svg?height=500&width=500",
    featured: true,
  },
  {
    id: "cup-soy-165",
    name: "100% Natural Soy Wax Cup Candle - 165g",
    description: "A 165g pure soy wax candle in a glass cup, eco-friendly and long-lasting.",
    category: "cup",
    waxType: "soy",
    weight: 165,
    price: 419,
    image: "/placeholder.svg?height=500&width=500",
  },

  // Cup Candles - 275g
  {
    id: "cup-gel-275",
    name: "Gel Wax Cup Candle - 275g",
    description: "A large 275g gel wax candle in a glass cup, perfect for creating ambiance.",
    category: "cup",
    waxType: "gel",
    weight: 275,
    price: 599,
    image: "/placeholder.svg?height=500&width=500",
  },
  {
    id: "cup-palm-275",
    name: "Palm Wax Cup Candle - 275g",
    description: "A 275g palm wax candle in a glass cup with a long burn time.",
    category: "cup",
    waxType: "palm",
    weight: 275,
    price: 570,
    image: "/placeholder.svg?height=500&width=500",
  },
  {
    id: "cup-soy-275",
    name: "100% Natural Soy Wax Cup Candle - 275g",
    description: "A 275g pure soy wax candle in a glass cup, environmentally friendly and aromatic.",
    category: "cup",
    waxType: "soy",
    weight: 275,
    price: 630,
    image: "/placeholder.svg?height=500&width=500",
    featured: true,
  },

  // Cup Candles - 300g
  {
    id: "cup-gel-300",
    name: "Gel Wax Cup Candle - 300g",
    description: "An extra-large 300g gel wax candle in a glass cup with stunning visual effects.",
    category: "cup",
    waxType: "gel",
    weight: 300,
    price: 719,
    image: "/placeholder.svg?height=500&width=500",
  },
  {
    id: "cup-palm-300",
    name: "Palm Wax Cup Candle - 300g",
    description: "A 300g palm wax candle in a glass cup, ideal for large spaces.",
    category: "cup",
    waxType: "palm",
    weight: 300,
    price: 680,
    image: "/placeholder.svg?height=500&width=500",
  },
  {
    id: "cup-soy-300",
    name: "100% Natural Soy Wax Cup Candle - 300g",
    description: "A 300g pure soy wax candle in a glass cup, perfect for gifting.",
    category: "cup",
    waxType: "soy",
    weight: 300,
    price: 785,
    image: "/placeholder.svg?height=500&width=500",
  },

  // Cup Candles - 320g
  {
    id: "cup-gel-320",
    name: "Gel Wax Cup Candle - 320g",
    description: "Our largest 320g gel wax candle in a glass cup, providing hours of beautiful light.",
    category: "cup",
    waxType: "gel",
    weight: 320,
    price: 820,
    image: "/placeholder.svg?height=500&width=500",
  },
  {
    id: "cup-palm-320",
    name: "Palm Wax Cup Candle - 320g",
    description: "A 320g palm wax candle in a glass cup with exceptional burn quality.",
    category: "cup",
    waxType: "palm",
    weight: 320,
    price: 790,
    image: "/placeholder.svg?height=500&width=500",
  },
  {
    id: "cup-soy-320",
    name: "100% Natural Soy Wax Cup Candle - 320g",
    description: "A 320g pure soy wax candle in a glass cup, our premium offering.",
    category: "cup",
    waxType: "soy",
    weight: 320,
    price: 860,
    image: "/placeholder.svg?height=500&width=500",
    featured: true,
  },

  // Shaped Candles
  {
    id: "shaped-bride",
    name: "Bride Shaped Candle",
    description: "A beautiful bride-shaped candle, perfect for wedding decorations or gifts.",
    category: "shaped",
    shape: "bride",
    price: 450,
    image: "/placeholder.svg?height=500&width=500",
  },
  {
    id: "shaped-cable",
    name: "Cable Shaped Candle",
    description: "A unique cable-shaped candle that adds a modern touch to any space.",
    category: "shaped",
    shape: "cable",
    price: 380,
    image: "/placeholder.svg?height=500&width=500",
  },
  {
    id: "shaped-ball",
    name: "Ball Shaped Candle",
    description: "A perfectly round ball-shaped candle available in various colors.",
    category: "shaped",
    shape: "ball",
    price: 350,
    image: "/placeholder.svg?height=500&width=500",
  },
  {
    id: "shaped-teddy",
    name: "Teddy Bear Shaped Candle",
    description: "An adorable teddy bear shaped candle, great for children's rooms or gifts.",
    category: "shaped",
    shape: "teddy",
    price: 420,
    image: "/placeholder.svg?height=500&width=500",
  },
  {
    id: "shaped-crescent",
    name: "Crescent Shaped Candle",
    description: "A beautiful crescent moon shaped candle for a magical atmosphere.",
    category: "shaped",
    shape: "crescent",
    price: 390,
    image: "/placeholder.svg?height=500&width=500",
  },
  {
    id: "shaped-lantern",
    name: "Lantern Shaped Candle",
    description: "A decorative lantern shaped candle, perfect for special occasions.",
    category: "shaped",
    shape: "lantern",
    price: 480,
    image: "/placeholder.svg?height=500&width=500",
  },
  {
    id: "shaped-skull",
    name: "Skull Shaped Candle",
    description: "A detailed skull shaped candle, ideal for Halloween or gothic decor.",
    category: "shaped",
    shape: "skull",
    price: 430,
    image: "/placeholder.svg?height=500&width=500",
  },
]

